version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_product
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_location
    columns:
      - name: address_id
        tests:
          - unique
          - not_null

  - name: fct_sales_per_order_line
    columns:
      - name: sales_order_detail_id
        tests:
          - unique
          - not_null

  - name: rep_monthly_sales
    description: "Monthly sales reporting table."